### PR TITLE
cmd/bosun: pass alert variables to unknown notification templates

### PR DESCRIPTION
**Pull request by harudark**
#2275 allows to pass alert variables to action notifications. 
This PR allows this for unknown and multiple unknown notifications.

### CODE REVIEW

**Comment by stepashka** [comment]
hey, @kylebrandt , @captncraig 
do you have any objections for merging this? we'd greatly appreciate that

**Comment by svagner** [comment]
It would be very useful to have this change

**Comment by svagner** [comment]
@muffix, @tdinucci We working with this change for a while and didn't noticed any problems. Do you have any objectives for this change? Can we merge it with the main?

**Comment by tdinucci** [comment]
@svagner we won't be able to accept this PR as it stands because there are no tests. We will still take a look though and consider it as soon as we can.

**Comment by svagner** [comment]
@tdinucci , thanks for the explanation! It makes great sense:)

**Pull request closed without merging**
