### PR TITLE
Added support for multi graphite data sources.

### PR DESCRIPTION
**Pull request by pradeepbbl**
This pull request will allow users to configure multiple Graphite backends similar to Elasticsearch. This requires a change in the existing Graphite config.

old config:
```
[GraphiteConf]
   Host = "localhost:80"
   [GraphiteConf.Headers]
           X-Meow = "Mix"
```

new config:
```
[GraphiteConf]
   [GraphiteConf.default]
       Host = "localhost:80"
       [GraphiteConf.default.Headers]
              X-Meow = "Mix"
```

Thanks,

### CODE REVIEW

**Comment by captncraig** [comment]
So this is definitely a breaking change? I'm ok with that we just need to be careful to highlight that.

**Comment by pradeepbbl** [comment]
@captncraig yup you are right it's a breaking change and error out in the startup, have also made a change to bosun config startup error to refer http://bosun.org/system_configuration for details.

**Comment by kylebrandt** [comment]
@pradeepbbl I think the CacheKey() needs to include the prefix or you might get false cache hits.

**Comment by pradeepbbl** [comment]
> @pradeepbbl I think the CacheKey() needs to include the prefix or you might get false cache hits.

@kylebrandt  thanks for reviewing, as suggested I have added Prefix to CacheKey.

**Comment by pradeepbbl** [comment]
@kylebrandt can this be merged now?

**Pull request closed without merging**
