### PR TITLE
Esfix

### PR DESCRIPTION
**Pull request by kylebrandt**

### CODE REVIEW

**Comment by kylebrandt** [comment]
Waiting on confirmation of fix from @awesensepaul before we should merge

**Comment by awesensepaul** [comment]
I can confirm that this fix is **awesome**! (and both commits/fixes were necessary to get correct ES 2.x behaviour).

FYI It is a huge relief to be able to use the same queries we use in Kibana (instead of re-writing them into regexes just for `bosun`).

Thanks!

**Comment by captncraig** [comment]
Merge anytime

**Comment by kylebrandt** [comment]
I forgot to pushed my rebased branch, already merged.

**Pull request closed without merging**
