### PR TITLE
Added ** expression operator -> q("q") ** 2 squares every element of the result query "q"

### PR DESCRIPTION
**Pull request by tkrajca**
Hi guys, added ** operator that runs math.Pow() on each element from a timeseries. Should all be pretty simple and standard. Let me know if this needs any work - formatting, docs, tests, etc. I am a python programmer so bosun and go are all pretty new to me. Cheers, Tomas

### CODE REVIEW

**Comment by gbrayut** [comment]
sorry... master branch was broken because build tags don't work like we thought they did. If you rebase this on the current master the travis ci check should work now.

**Comment by tkrajca** [comment]
Should be good now, cheers.

**Comment by kylebrandt** [comment]
The standard arithmetic order of operations needs to be maintained. Currently that is not the case. Exponentiation should take precedence over multiplication, but it doesn't. So the following should be true, but isn't in the branch:

image

**Comment by tkrajca** [comment]
Thanks @kylebrandt, good catch, that should be fixed now.

**Comment by kylebrandt** [comment]
@tkrajca Can you rebase this on master? Will test one more time after rebase and then should be good to go.

**Comment by tkrajca** [comment]
@kylebrandt I got quite a few merge conflicts when rebasing so I created a new branch of master Pow_operator2 and put all my changes in there as PR https://github.com/bosun-monitor/bosun/pull/1674

**Pull request closed without merging**
