### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by captncraig**

### CODE REVIEW

**Comment by giganteous** [comment]
You could change the import for snmp to bosun-monitor/snmp now? I don't know if it fits in your schedule though.

**Comment by captncraig** [comment]
Yeah, I'll be doing that. Actually playing with godep instead of party for vendoring at the moment. I'll move snmp as part of that.

**Comment by giganteous** [comment]
godep or gb :). :+1: for anything that uses a 'vendor' dir, and no rewriting.

**Comment by captncraig** [comment]
@giganteous we are probably going to stick with rewriting until GOVENDOREXPERIMENT becomes a default. Maybe. It is important to us that `go get bosun.org.cmd.bosun` works for people.

Setting the env var is not difficult, but it is another step. Bring it up in slack if you feel strongly.

**Pull request merged**
