### PR TITLE
cmd/bosun: purge old incident state

### LINKED ISSUE #2363: Incident state stored forever
Once an incident is raised and closed, its state is stored forever.  This can chip away at memory available in Redis over time.  There should be a mechanism to cleanup old `incidentById:*` keys, similar to what `MaxRenderedTemplateAge` provides for rendered templates.

### PR DESCRIPTION
**Pull request by neilfordyce**
Based on the ideas introduced in https://github.com/bosun-monitor/bosun/pull/2167, this allows purging of keys under incidentById:*.  State for closed incidents which are beyond retention will be removed if the MaxClosedIncidentAge option is specified.

This fixes #2363.  It's discussed in #1974.

### CODE REVIEW

**Comment by kylebrandt** [comment]
I think the PreviousIds will need to be walked and and any links to purged incident states will need to be updated.  Do you have any ideas on how much memory this taking for you? Moving the rendered templates out was the bulk of it for us.

**Comment by neilfordyce** [comment]
Thanks for the feedback.  

We have a Bosun instance which has been running for around 2 years.  We deployed the changes in this PR with a six month closed incident retention and reclaimed about 0.5GB.  For comparison, when we added a one month rendered template retention we removed about 1GB.  We decided to add this after doing a `--bigkeys` scan on our Redis DB and finding a single incidentById key which was almost 50MB.  We have a few alerts with high cardinality groups, which causes the "Events" list in the incident blob to blow up.

There is an attempt to cleanup links to deleted incidents in `deleteIncidentReferences()`, but maybe I missed something else.  This should take care of the references returned by `GetAllIncidentIdsByAlertKey()`.  Please let me know if there is more to cleanup and I can have a look.

**Comment by kylebrandt** [comment]
@neilfordyce I don't think that covers it ... (although relational stuff in redis is confusing).

models.IncidentState has `PreviousIds []int64` property. This property contains a list of all incident ids that came before it. So an incident that hasn't been removed would have a incident entry in that link that is a dead link unless the incidents that are not getting deleted have that property updated.

**Comment by neilfordyce** [comment]
Thanks for the feedback.  I added some cleanup for the references in PreviousIds of alerts with the same alert keys.

**Pull request closed without merging**
