### PR TITLE
Introduced DisableMetadata configuration property

### PR DESCRIPTION
**Pull request by GROpenSourceDev**
This allows you to externally configure if you would like to disable sending metadata to TSDB. We also wrapped an existing call with the internal flag which appeared to be missing.

### CODE REVIEW

**Comment by kylebrandt** [comment]
@GROpenSourceDev Side not, not ignoring your PRs. Just pushing towards our next release so want to save this and the other PR for a follow up release. Also am waiting for the person that does most of the windows+scollector work to get back from vacation/conference.

tldr: your patience and contributions are very much appreciated!

**Comment by GROpenSourceDev** [comment]
@kylebrandt No problem, thanks for letting us know.

**Comment by captncraig** [comment]
One thing I'd like to see: If metadata is disabled and never sending, the in-memory collections in the metadata package will still fill up and consume memory. Would be nice if AddMeta in the metadata package would no-op if the flag is set.

**Comment by GROpenSourceDev** [comment]
@captncraig we've made the change as suggested. Thanks

**Comment by GROpenSourceDev** [comment]
@captncraig @kylebrandt Hi, Is it possible to have an update on this PR? We're keen to move back onto Master if possible. Thanks

**Pull request closed without merging**
