### PR TITLE
cmd/scollector: Added collector for GitHub Enterprise

### PR DESCRIPTION
**Pull request by mhenderson-so**

### CODE REVIEW

**Comment by mhenderson-so** [comment]
Uhh, I didn't change `cmd/bosun`. Is this a repeat of previous issue where the go generate always reports a change, even when there isn't one?

**Comment by captncraig** [comment]
I think esc made some changes. Try `go get -u -v github.com/mjibson/esc`

**Comment by captncraig** [comment]
There's an extra debug file to delete.

**Comment by mhenderson-so** [comment]
Which extra debug file is there to delete? I removed one that was already in there but I don't see any others?

Regarding `go generate`  I'm getting a heap of errors trying to run this on Windows. I don't know if this is a Windows thing, or if my particular setup is borked:

```
[88] H:\Go\src\bosun.org\cmd\scollector> go generate bosun.org/...
# bosun.org/vendor/golang.org/x/sys/windows
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:38: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:39: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:40: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:41: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:42: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:43: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:44: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:45: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:46: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:47: undefined: NewLazySystemDLL
..\..\vendor\golang.org\x\sys\windows\zsyscall_windows.go:47: too many errors
..\bosun\main.go:3: running "go": exit status 2
2017/09/25 09:24:56 open ../ui/include.partial.html: The system cannot find the path specified.
..\..\vendor\github.com\MiniProfiler\go\miniprofiler\miniprofiler.go:348: running "esc": exit status 1
GetFileAttributesEx ../model/cli/gen-endpoints/main.go: The system cannot find the path specified.
..\..\vendor\github.com\aws\aws-sdk-go\private\endpoints\endpoints.go:4: running "go": exit status 1
GetFileAttributesEx ../../../models/protocol_tests/generate.go: The system cannot find the path specified.
..\..\vendor\github.com\aws\aws-sdk-go\private\protocol\ec2query\build.go:4: running "go": exit status 1
GetFileAttributesEx ../../../models/protocol_tests/generate.go: The system cannot find the path specified.
..\..\vendor\github.com\aws\aws-sdk-go\private\protocol\query\build.go:4: running "go": exit status 1
GetFileAttributesEx ../../../models/protocol_tests/generate.go: The system cannot find the path specified.
..\..\vendor\github.com\aws\aws-sdk-go\private\protocol\restxml\restxml.go:5: running "go": exit status 1
..\..\vendor\github.com\influxdata\influxdb\influxql\influxql.go:3: running "tmpl": exec: "tmpl": executable file not found in %PATH%
..\..\vendor\github.com\jmespath\go-jmespath\lexer.go:51: running "stringer": exec: "stringer": executable file not found in %PATH%
GetFileAttributesEx ../_codegen/main.go: The system cannot find the path specified.
..\..\vendor\github.com\stretchr\testify\assert\forward_assertions.go:16: running "go": exit status 1
ls: cannot access 'values_test.go': No such file or directory
ls: cannot access 'values_test.go': No such file or directory
ls: cannot access 'values_test.go': No such file or directory
cp: cannot stat '/mnt/h/Go/src/bosun.org/vendor/github.com/ugorji/go/codec/values_test.go': No such file or directory
```

**Pull request closed without merging**
