### PR TITLE
fix nilpointer check being too late

### PR DESCRIPTION
**Pull request by Dieterbe**

### CODE REVIEW

**Comment by Dieterbe** [comment]
actually sorry, i pushed this a bit too early.
the `wait := time.After(s.Conf.CheckFrequency)` should also be after the nil check (and after the "sched: frequency must be > 1 second") check.  and i also noticed the `if s.Conf.Ping` higher up in this function. maybe we should just move the `if s.Conf == nil` check to the beginning of this function.

**Comment by Dieterbe** [comment]
and while we're at it, we could also just construct a time.Ticker before the loop and just range over its messages.

**Comment by mjibson** [comment]
The wait should move, yes, but that's it. s.Conf should be checked each time because it is theoretically possible that something removed it. The wait time also needs to be calculated each time because it's possible that something changed the wait interval. We don't currently have that functionality, but this code protects against that.

The ticker won't work because if you don't have anything to receive the tick, it gets dropped on the ground. If a run takes longer than the check frequency, we don't want to skip a run, we just want to run one immediately again. Say a run takes 6 minutes, and you have a 5 minute check time. With a ticker, you'll get runs every 10 minutes, because the 5 minute ticks will be dropped since they don't have a listener. With the current model you'll get runs every 6 minutes, which is fine.

**Comment by Dieterbe** [comment]
ok, I brought these things up because i suspected some things like that might be going on :+1:

**Pull request merged**
