### PR TITLE
Autoclose flag + Normal notifications

### PR DESCRIPTION
**Pull request by crandles**
This PR addresses issues in: #333, #1607.

We are also using bosun as a way to relay alerts to various systems operated by different NOC teams; the external systems are used for incident management instead of Bosun, so in this instance we end up ignoring Bosun's state machine.

This PR exposes an "autoclose" flag at the alert configuration that will cause any normal events to close an already open incident related with the event. If a normNotification is configured, it will be used to relay the message a la critNotification/warnNotification.

### CODE REVIEW

**Comment by kylebrandt** [comment]
I worry about doing anything that changes the incident state machine. There are already enough interactions with notification chains and various flags that I am worried about changes there.

What I think would be best would be some sort of incident subscription endpoint where Bosun just sends all events to an endpoint (and/or one where you can poll all events from the past X minutes). That makes it so Bosun can keep it's workflow, but you can use something instead to handle severity state logic in the way you see fit

**Comment by crandles** [comment]
That's valid -- I'd prefer the "incident subscription endpoint" over having a specific API to poll. 

Where would you see that fitting in to the codebase?

**Comment by crandles** [comment]
As far as usage, what about something like:
```
notification nocAPI {
	post = http://internal.noc.api:1234/
	contentType = application/json
}

template payload.json {
	subject = `{"name" : "{{.Alert.Name}}","instance" : "{{ .Group.instance }}", "status" : "{{.CurrentStatus}}", "output":"{{ .Alert.Vars.message }}"}`
}

alert myapp.errors {
	$message = `In the last 30 seconds there have been more than 10 errors.`
	$q = first(influx("vde",'''SELECT SUM(total) FROM "errors" GROUP BY error''',"30s","","15s"))
	crit = $q > 10
	template = payload.json
	eventNotification = nocAPI
}
```

**Comment by ankitm7** [comment]
We are planning to use this feature. When is it planned to merge this feature to bosun:master ?

**Comment by kylebrandt** [comment]
This will need to be a fork for a while I'm afraid. My best estimate right now would be the summer. This is because the incident state code really needs to be refactored into a proper state machine. Currently it has some bugs, and adding things to it in the current state is not safe I don't believe.

**Comment by Dieterbe** [comment]
>  is not safe I don't believe.

Yeay for safe and double negatives

**Comment by rohit01** [comment]
@kylebrandt @crandles I am also facing this issue. Any plans to merge this?

**Comment by pradeepbbl** [comment]
+100

**Comment by seanlook** [comment]
I have this feature `DelayCloseNormal` with my fork: https://github.com/seanlook/bosun .

Feel free to try it☺

**Comment by svagner** [comment]
Any progress on this MR?

**Comment by crandles** [comment]
No progress from my side. I have stopped using bosun at this point, and haven't been following updates. This seems related: https://github.com/bosun-monitor/bosun/commit/90cc3a91776fec5f86f1f85032c29eac6710dfc8 but I'm not sure if it covers the same functionality I originally needed.

**Comment by svagner** [comment]
> No progress from my side. I have stopped using bosun at this point, and haven't been following updates. This seems related: [90cc3a9](https://github.com/bosun-monitor/bosun/commit/90cc3a91776fec5f86f1f85032c29eac6710dfc8) but I'm not sure if it covers the same functionality I originally needed.

For me it looks like absolutely different functionality. @kylebrandt do you have some objections for autoclose incidents. I mean by design of bosun is it possible to have this functionality?

**Pull request closed without merging**
