### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### bosun-monitor/bosun now has a Chat Room on Gitter

@captncraig has just created a chat room. You can visit it here: [https://gitter.im/bosun-monitor/bosun](https://gitter.im/bosun-monitor/bosun?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/bosun-monitor/bosun?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Dieterbe** [comment]
wait so are we now no longer using slack or what?

**Comment by kylebrandt** [comment]
image

**Comment by kylebrandt** [comment]
image

**Comment by captncraig** [comment]
I just made a gitter room to see how it works. If people want to migrate there it would remove the need to have the odd invite thing, and would apparently give unlimited history and stuff that slack charges for. 

Not sure about the performance of it though.

**Comment by captncraig** [comment]
Sorry @kylebrandt. I really don't have enough pain with slack to move off. Just exploring possibilities.

**Comment by Dieterbe** [comment]
i think @kylebrandt was using these images to suggest "stop bikeshedding" ?
FWIW i don't think we're bikeshedding here.
anyway carry on.

**Pull request closed without merging**
