### PR TITLE
support for LDAP user authentication.

### PR DESCRIPTION
**Pull request by pradeepbbl**
@captncraig

### CODE REVIEW

**Comment by captncraig** [comment]
I think just needs `govendor update github.com/captncraig/easyauth/...`

**Comment by pradeepbbl** [comment]
@captncraig  yes, do I need to run this in my branch or it will auto took care by the test script?

**Comment by captncraig** [comment]
Yeah, you need to check in the updated library files to the `vendor` folder.

**Comment by pradeepbbl** [comment]
@captncraig could please let me know when this will be merged.

-Thanks

**Pull request merged**
