### PR TITLE
Added ** expression operator -> q("q") ** 2 squares every element of …

### PR DESCRIPTION
**Pull request by tkrajca**
…the result query "q"

This superseded https://github.com/bosun-monitor/bosun/pull/1645 as there were many merge conflicts during rebase.

### CODE REVIEW

**Comment by kylebrandt** [comment]
needs gofmt

**Comment by tkrajca** [comment]
@kylebrandt should be done

**Comment by kylebrandt** [comment]
Will gofmt and merge into the release after 0.5.0

**Comment by kylebrandt** [comment]
added via #1795

**Pull request closed without merging**
