### PR TITLE
Fix crashing in Limit and reduce functions

### PR DESCRIPTION
**Pull request by svagner**
Hi! We've caught 2 panics of bosun related with some combination of incoming data from graphite and rules of alerting.
# Panic 1: 
```
error: expr.go:142: Error: interface conversion: expr.Value is expr.Number, not expr.Series. Origin: Schedule: Alert Name: nettools_memory. Expression: max(max(graphite("aliasByNode(movingAverage(sys.hostname*.memory.MemTotal, 4), 1)", "20m", "5m", "host") - graphite("aliasByNode(movingAverage(sys.{netshell,netmon,nettools}.memory.MemFree, 4), 1)", "20m", "5m", "host") + graphite("aliasByNode(movingAverage(sys.hostname*.memory.Cached, 4), 1)", "20m", "5m", "host")) / graphite("aliasByNode(movingAverage(sys.hostname*.memory.MemTotal, 4), 1)", "20m", "5m", "host") * 100) > 90.0, Stack: goroutine 496765 [running]:  
...
/usr/lib64/go/src/runtime/panic.go:513 +0x1b9  
bosun.org/cmd/bosun/expr.reduce.func1(0xc0afc47680, 0xc0afc47560, 0xc015b8c448, 0x1, 0x1, 0xc015b8c448, 0x0)  
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/expr/funcs.go:1034 +0x1b6  
bosun.org/cmd/bosun/expr.match(0xc05d57ee40, 0xc0afc46930, 0xc0eb7a3528, 0x1, 0x1, 0xc0afc47620, 0x40e058, 0x30)  
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/expr/funcs.go:1025 +0x414  
bosun.org/cmd/bosun/expr.reduce(0xc11b213540, 0xc0afc46930, 0x1520858, 0xc0eb7a3528, 0x1, 0x1, 0xe30fef, 0xc0eb7a35b0, 0x40d7cf)  
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/expr/funcs.go:1042 +0x83  
bosun.org/cmd/bosun/expr.Max(0xc11b213540, 0xc0afc46930, 0x0, 0x0, 0x0)  
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/expr/funcs.go:1349 +0x13d  
reflect.Value.call(0x10dbfa0, 0x15206f0, 0x13, 0x12a5ea7, 0x4, 0xc0afc475f0, 0x2, 0x2, 0x0, 0xc0afc475f0, ...)  
... 
bosun.org/cmd/bosun/expr.(*State).walkFunc.func1(0x16200a0, 0xc00d816b40)  
/builddir/build/BUILD/bosun-0.8.0/GO/src/bosun.org/cmd/bosun/expr/expr.go:783 +0xe70  
``` 
## How to repeat problem:
Rules:
```
alert panic {
    # ...
    runEvery = 1
    $badness_by_host = "test"
    $free_memory = graphite("aliasByNode(movingAverage(sys.hostname-*.memory.MemFree, 4), 1)", "20m", "5m", "host")
    $total_memory = graphite("aliasByNode(movingAverage(sys.hostname-*.memory.MemTotal, 4), 1)", "20m", "5m", "host")
    $cached_memory = graphite("aliasByNode(movingAverage(sys.hostname-*.memory.Cached, 4), 1)", "20m", "5m", "host")
    $used_memory = max($free_memory + $cached_memory)
    $usage_perc = max($used_memory / $total_memory * 100)
    warn = $usage_perc > 80
    crit = $usage_perc > 95
```
Script for emulate graphite responses:
```
#!/usr/bin/env python
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
import SocketServer

class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        data = '[{"target":"hoss.dc","datapoints":[[2, 534612462], [0, 1541667067]]}]'
        if self.path.find("MemTotal") >= 0:
            data = '[{"target":"host.dc","datapoints":[[2, 534612462], [0, 1541667067]]}]'
        self.wfile.write(data.encode())

def run(server_class=HTTPServer, handler_class=S, port=80):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()

if __name__ == "__main__":
    run()
```
## Description of problem
Basically condition from alert should go by follow way:
- max(..) - walkFunc
- max(..) / graphite(..) - walkBinary
- etc.

In method walkBinary we are calling method union and passing 2 args: Numeric (result of max(..)) and Serial (result of graphite(...)). Inside union we are generating unjoined Union structures with fields - A = A, B = NaN(). It cat happen if condition len(ra.Group) == len(rb.Group) as example return true.  If 'A' was Numeric, we will give structure Union{A: Numeric, B: Numeric}. Result of this in walkBinary will be Numeric. As result we are passing Numeric to walkFunc (Max()).

## Fix:
reduce should validate that only seriesValue was passed as argument.

# Panic 2:
```
error: expr.go:142: Error: runtime error: slice bounds out of range. Origin: Schedule: Alert Name: oor_panic. Expression: sum(limit(graphite("aliasByNode(aliasSub(perSecond(transformNull(general.data.*.some.data)), '_', '.'), 2, 3)", "20m", "", "host.dc"), 20 - 40) * 100) > 0, Stack: goroutine 62 [running]:
runtime/debug.Stack(0x10e9240, 0x10d3500, 0x1cd9dc0)
/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
bosun.org/cmd/bosun/expr.errRecover(0xc4201ade58, 0xc4201e8000)
src/bosun.org/cmd/bosun/expr/expr.go:142 +0x22f
panic(0x10d3500, 0x1cd9dc0)
/usr/local/go/src/runtime/panic.go:502 +0x229
bosun.org/cmd/bosun/expr.Limit(0xc4201e8000, 0xc420457d70, 0xc034000000000000, 0x0, 0x0, 0x0)
src/bosun.org/cmd/bosun/expr/funcs.go:773 +0x4d
reflect.Value.call(0x10d0e00, 0x1524cf8, 0x13, 0x12aacfb, 0x4, 0xc420309c20, 0x3, 0x3, 0xc034000000000000, 0xc420309c20, ...)
/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x10d0e00, 0x1524cf8, 0x13, 0xc420309c20, 0x3, 0x3, 0x2, 0x2, 0xc420290380)
/usr/local/go/src/reflect/value.go:308 +0xa4
bosun.org/cmd/bosun/expr.(*State).walkFunc.func1(0x15c7a00, 0xc420400090)
src/bosun.org/cmd/bosun/expr/expr.go:791 +0xffd
bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler.(*Profile).Step(0xc420400090, 0xc420290380, 0xb, 0xc4202f25c0)
src/bosun.org/vendor/github.com/MiniProfiler/go/miniprofiler/types.go:195 +0x76
bosun.org/cmd/bosun/expr.(*State).walkFunc(0xc4201e8000, 0xc420085a40, 0x1)
src/bosun.org/cmd/bosun/expr/expr.go:743 +0x10c
bosun.org/cmd/bosun/expr.(*State).walk(0xc4201e8000, 0x15c8e40, 0xc420085a40, 0xc420062cf8)
src/bosun.org/cmd/bosun/expr/expr.go:495 +0x13f
bosun.org/cmd/bosun/expr.(*State).walkBinary(0xc4201e8000, 0xc420031380, 0x0)
src/bosun.org/cmd/bosun/expr/expr.go:517 +0x5a
bosun.org/cmd/bosun/expr.(*State).walkFunc.func1(0x15c7a00, 0xc420400090)
src/bosun.org/cmd/bosun/expr/expr.go:757 +0x5cc
```
## How to repeat problem:
Rules:
```
alert oor_panic {
    $search_metric = aliasSub(perSecond(transformNull(general.data.*.some.data)), '_', '.')
    $data = graphite("aliasByNode($search_metric, 2, 3)", "20m", "", "host.dc")
    $badness_by_host = sum(limit($data, 20 - 40) * 100)
    warn = $badness_by_host > 0
    crit = $badness_by_host > 0
}
```
Script for emulate graphite responses: from preview panic (there doesn't matter graphite data for reproduce problem)

## Description of problem:
There is no validation that second argument that passed to Limit function is positive. We are usinng this argument as second index in slice (e.g. set.Results[:i]). Golang doesn't allow usage of negative indices in slice definition. Examples of errors: Runtime: https://play.golang.org/p/Go5SgBt-KeJ, Parser: https://play.golang.org/p/Ut-BrP1_ymP

## Fix:
Limit function shouldn't allow negative values as argument, because implementation of slices in golang doesn't allow it

### CODE REVIEW

**Comment by svagner** [comment]
Hi  @kylebrandt , @captncraig! 
Do you agree to apply those small fixes?:)

**Comment by kylebrandt** [comment]
Limit fix is good. Regarding the check on `reduce`, I don't think that *should* be needed as the Tag functions on all the arguments should stop that from happening. Need to see why that isn't working in this case.

**Comment by svagner** [comment]
Basically parser is really throw error if there is incorrect arg type, but it works only in case like:
max(Number(10)). There is problem when we are passing result of WalkBinary to WalkFunc. I also thought to change logic here - https://github.com/bosun-monitor/bosun/blob/3ee0cb0196ba68d1836dfab248200f2b72e79079/cmd/bosun/expr/expr.go#L461 and here - https://github.com/bosun-monitor/bosun/blob/3ee0cb0196ba68d1836dfab248200f2b72e79079/cmd/bosun/expr/expr.go#L472. NaN() will return Numeric anyway. So may be we should review NaN method for return NaN for slices as empty slice...

**Comment by stepashka** [comment]
Hey @kylebrandt @captncraig !
Any objections to merging this? :)

**Pull request merged**
