### PR TITLE
Pass IncidentState to notifications for richer templating

### PR DESCRIPTION
**Pull request by gnosek**
This series adds `useFullContext` notification setting. If it's set to true, instead of the template subject/body, the notification template gets passed the whole IncidentState. This allows for richer notifications, e.g.:

```
template common {
    subject = {{.Alert.Vars.title}} on {{.Group.host}}
    body = `<h1><a href="{{.Incident}}">[{{.Last.Status}}] {{.Alert.Vars.title}} on {{.Group.host}}</a></h1>`
}

notification some_webservice {
    post = http://localhost:8000/some_webservice
    useFullContext = true
    body = `{
        "author": "Bosun",
        "thread_id": "{{.AlertKey}}",
        "status": "{{.CurrentStatus}}",
        "subject": "{{.Subject}}",
        "body": {{.Body|json}}
    }`
    contentType = application/json
}
```

### CODE REVIEW

**Comment by gnosek** [comment]
Not sure I understand what actually failed in the Travis build :(

**Comment by gnosek** [comment]
Oh, it was gofmt, should be fixed now.

**Comment by gnosek** [comment]
gofmt is happy but Travis is not :/

**Comment by captncraig** [comment]
I believe we want to solve this problem a slightly different way, by allowing an template to define an arbitrary set of subtemplates, and the notification then just needs to pick which one, or maybe something like that. It is hard to do in a way that decouples notifications from alerts. Planning to address this for the next release.

**Comment by kylebrandt** [comment]
will be fixed with https://github.com/bosun-monitor/bosun/pull/2135

**Pull request closed without merging**
