### PR TITLE
Pop the free ID when assigning to a process

### LINKED ISSUE #2128: BUG: Linux process monitoring ID assignment broken after a process quits
See - https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/processes_linux.go#L355

After the first monitored process quits, the ID assigned to it is added to the list `free`. When the next process starts it is assigned the smallest ID from `free` but that ID is not removed, so all future processes receive the same ID.

### PR DESCRIPTION
**Pull request by bharrisau**
Fixes #2128.

### CODE REVIEW

**Comment by captncraig** [comment]
Yes, I believe this has been causing us some trouble as well. Thanks for tracking it down. I believe the build is failing because it needs to have gofmt run on the changed file.

**Comment by bharrisau** [comment]
@captncraig I did this quickly just using the github website (seems like I left whitespace on the empty lines). I don't have any Go toolchain setup locally.

Would you be able to take it from here? And check the windows and osx implementations don't have the same issue? Otherwise I may have some time next week to set things up.

**Comment by bharrisau** [comment]
@captncraig Managed to make Travis green. Is this ok to merge?

**Comment by captncraig** [comment]
Yeah, let's do it.

**Pull request merged**
