### PR TITLE
Have opentsdb.Duration implement encoding.TextUnmarshaler.

### PR DESCRIPTION
**Pull request by alienth**
:eyeglasses: @captncraig  @kylebrandt 

Will be using this to read durations from a config file on a separate utility.

### CODE REVIEW

**Comment by captncraig** [comment]
Lgtm

**Comment by kylebrandt** [comment]
If non blocking I'd like to review in morning before merge

**Comment by alienth** [comment]
Not sure if I'll be around during your morning time. Mind prodding at this via comments?

**Comment by kylebrandt** [comment]
Nope don't mind that was my plan, sorry for not being clear. Just out
tonight so couldn't review until morning

On Nov 30, 2016 20:49, "Jason Harvey" <notifications@github.com> wrote:

>

> Not sure if I'll be around during your morning time. Mind prodding at
this via comments?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/bosun-monitor/bosun/pull/1975#issuecomment-264054728>,
or mute the thread

**Comment by alienth** [comment]
Gotcha, works for me. Thanks!

**Pull request merged**
